name: Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      env:
        IMAGE: "kalemena/cadquery"
        VERSION: "latest"
      run: |
        sh .github/workflows/build.sh
        # PUSH
        docker login -u "${GITHUB_ACTOR}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker push ${IMAGE}:${VERSION}
        docker push ${IMAGE}:latest
        docker logout